on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    steps:
      - name: Verifica o repositótio do Git
        uses: actions/checkout@v2
      
      - name: Instala o node com versão
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Instalando dependencias
        run: npm install

      - name: executando o lint
        run: npm run lint
